{
    "label": "unknown",
    "execution_time": 248.79403567314148,
    "error": "Traceback (most recent call last):\n  File \"/4tb/dowon/PRISM_evaluation/scripts/patchsim.py\", line 257, in run\n    result[\"label\"] = f.readlines()[-1].strip()\n                      ~~~~~~~~~~~~~^^^^\nIndexError: list index out of range\n"
}